### ISSUE TITLE
when disabled timeout it always throw error

### ISSUE THREAD

**Issue by mix5003** [wongnai/eastern#22]
when i use `eastern job --timeout 0 migrate_job.yaml default $BITBUCKET_COMMIT`. it ran job normally but it throw an error below. 

```job.batch/database-migrate-job-5d74557cd710d188aaadfc3ebbcc9b89300555d6 created
Cleaning up job database-migrate-job-5d74557cd710d188aaadfc3ebbcc9b89300555d6
job.batch "database-migrate-job-5d74557cd710d188aaadfc3ebbcc9b89300555d6" deleted
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/eastern-4.4.1-py3.7.egg/eastern/timeout.py", line 34, in run
  File "/usr/local/lib/python3.7/site-packages/eastern-4.4.1-py3.7.egg/eastern/timeout.py", line 66, in set_timeout
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 651, in call_later
    timer = self.call_at(self.time() + delay, callback, *args,
TypeError: unsupported operand type(s) for +: 'float' and 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/eastern", line 11, in <module>
    load_entry_point('eastern==4.4.1', 'console_scripts', 'eastern')()
  File "/usr/local/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click-6.7-py3.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/eastern-4.4.1-py3.7.egg/eastern/cli.py", line 223, in job
  File "/usr/local/lib/python3.7/site-packages/eastern-4.4.1-py3.7.egg/eastern/job_manager.py", line 78, in wait_completion
  File "/usr/local/lib/python3.7/site-packages/eastern-4.4.1-py3.7.egg/eastern/timeout.py", line 20, in run_sync
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/eastern-4.4.1-py3.7.egg/eastern/timeout.py", line 53, in run
AttributeError: 'ProcessTimeout' object has no attribute '_timeout'```

**Comment by whs** [comment]
As a workaround you can set the timeout to large value, which is what we're using now as well (and there are still misbehaving jobs hitting that limits...)
